-- Script para insertar categorías en la base de datos
-- Ejecutar este script en tu base de datos

INSERT IGNORE INTO categories (id, name, created_at, updated_at) VALUES
(1, 'Electrónicos', NOW(), NOW()),
(2, 'Ropa y Accesorios', NOW(), NOW()),
(3, 'Hogar y Jardín', NOW(), NOW()),
(4, 'Deportes y Fitness', NOW(), NOW()),
(5, 'Libros y Medios', NOW(), NOW()),
(6, 'Salud y Belleza', NOW(), NOW()),
(7, 'Juguetes y Juegos', NOW(), NOW()),
(8, 'Automotriz', NOW(), NOW()),
(9, 'Alimentación', NOW(), NOW()),
(10, 'Oficina y Escolar', NOW(), NOW()),
(11, 'Tecnología', NOW(), NOW()),
(12, 'Muebles', NOW(), NOW()),
(13, 'Herramientas', NOW(), NOW()),
(14, 'Jardinería', NOW(), NOW()),
(15, 'Cocina', NOW(), NOW()),
(16, 'Baño', NOW(), NOW()),
(17, 'Dormitorio', NOW(), NOW()),
(18, 'Salón', NOW(), NOW()),
(19, 'Iluminación', NOW(), NOW()),
(20, 'Decoración', NOW(), NOW()),
(21, 'Textiles', NOW(), NOW()),
(22, 'Alfombras', NOW(), NOW()),
(23, 'Cortinas', NOW(), NOW()),
(24, 'Electrodomésticos', NOW(), NOW()),
(25, 'Climatización', NOW(), NOW()),
(26, 'Seguridad', NOW(), NOW()),
(27, 'Limpieza', NOW(), NOW()),
(28, 'Organización', NOW(), NOW()),
(29, 'Bricolaje', NOW(), NOW()),
(30, 'Ferretería', NOW(), NOW());
(30, 'Aseo', NOW(), NOW());
